#pragma once

// Header-defined bootstrap codegen subsystems. They are included from exactly
// one translation unit so the existing CodeGen member definitions stay unique
// while the core driver/support code can live in smaller .cpp files.
#include "../runtime/value_casts.h"
#include "../types/type_shape.h"
#include "../arrays/access.h"
#include "../arrays/index_address.h"
#include "../arrays/append_intrinsic.h"
#include "../arrays/array_literal.h"
#include "../arrays/index_value.h"
#include "../arrays/std_intrinsics.h"
#include "../assignment/assign.h"
#include "../expressions/binary.h"
#include "../expressions/unary.h"
#include "../runtime/call_expr.h"
#include "../runtime/cast_expr.h"
#include "../runtime/c_symbols.h"
#include "../runtime/len_intrinsic.h"
#include "../runtime/new_intrinsic.h"
#include "../formatting/printf.h"
#include "../formatting/println.h"
#include "../formatting/sprintf.h"
#include "../loops/for_stmt.h"
#include "../loops/c_style_for_stmt.h"
#include "../loops/for_in_stmt.h"
#include "../functions/declarations.h"
#include "../functions/type_resolver.h"
#include "../branches/if_stmt.h"
#include "../literals/literal.h"
#include "../postfix/postfix.h"
#include "../structures/declarations.h"
#include "../structures/type_resolver.h"
#include "../variables/declarations.h"
